### PR TITLE
Update Scintilla

### PR DESCRIPTION
**Pull request by data-man**
Taked from Mercurial repository.

### CODE REVIEW

**Comment by data-man** [comment]
Unrelated note: currently I can't install Textosaurus by make (in Linux).

**Comment by data-man** [comment]
Updated to Scintilla 4.4.5 (released 11 September 2020).

**Comment by martinrotter** [comment]
> Unrelated note: currently I can't install Textosaurus by make (in Linux).

Can you ellaborate? Make is used even on CI/Linux in Travis and it all works there. Also, no Linux distro's maintainers complained, it should all work.

**Comment by data-man** [comment]
> Also, no Linux distro's maintainers complained

According to [repology/textosaurus](https://repology.org/project/textosaurus/versions) only Arch Linux and Void Linux has textosaurus package.
I'm Arch Linux user, but [AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=textosaurus-git) is incorrect, IMO.
Because uses your old Scintilla fork for building.
As I see, Void Linux [does](https://github.com/void-linux/void-packages/blob/master/srcpkgs/textosaurus/template) the same.

So I compiles by hand. :)
But I don't use git submodules and doubt that's the problem.

**Comment by martinrotter** [comment]
Yes, that AUR package is clearly outdated. What can I do. :)

Compile by hand or perhaps use AppImage if it does the job for you.

**Pull request merged**
