### PR TITLE
Some updates

### PR DESCRIPTION
**Pull request by data-man**
- update md4c to latest
- update UCD to 14.0 (current beta)

I can update UCD to latest release (13.0) if you wish.

Thank you for the project!

### CODE REVIEW

**Comment by martinrotter** [comment]
@data-man Thank you very much, it looks just fine. Merging.

**Comment by data-man** [comment]
@martinrotter What do you think about Scintilla updates?

**Comment by martinrotter** [comment]
Well, I do them from time to time. Are there any new features/fixes you need?

**Comment by data-man** [comment]
Yes, would be nice.
Especially "Optimized performance when opening huge files." in release 4.4.0 (1 June 2020).

BTW, latest release is 4.4.4 (21 July 2020).

**Comment by data-man** [comment]
Just now I compiled Textosaurus with Scintilla from Mercurial repo.

I can do PR if you don't mind.

**Comment by martinrotter** [comment]
Sure, you can, will be happy to merge. I believe, that I do not do any customizations, just plain vanilla Scintilla from their repos.

**Comment by data-man** [comment]
Are you Windows user?
I'm not, so Cr-Lf problem in sources. :)

**Pull request merged**
